//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.FriendServiceSoap")]
    public interface FriendServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FriendInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FriendInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FriendInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> FriendInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFriendList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetFriendList(string prefixText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFriendList", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetFriendListAsync(string prefixText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FriendServiceSoapChannel : Facebook.ServiceReference1.FriendServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FriendServiceSoapClient : System.ServiceModel.ClientBase<Facebook.ServiceReference1.FriendServiceSoap>, Facebook.ServiceReference1.FriendServiceSoap {
        
        public FriendServiceSoapClient() {
        }
        
        public FriendServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FriendServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FriendInfo() {
            return base.Channel.FriendInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FriendInfoAsync() {
            return base.Channel.FriendInfoAsync();
        }
        
        public string[] GetFriendList(string prefixText) {
            return base.Channel.GetFriendList(prefixText);
        }
        
        public System.Threading.Tasks.Task<string[]> GetFriendListAsync(string prefixText) {
            return base.Channel.GetFriendListAsync(prefixText);
        }
    }
}
