//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEEntity.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public Option()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public byte oid { get; set; }
        public string name { get; set; }
        public byte qid { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
