//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEEntity.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Options = new HashSet<Option>();
            this.Options1 = new HashSet<Option>();
        }
    
        public byte qid { get; set; }
        public string name { get; set; }
        public byte marks { get; set; }
    
        public virtual ICollection<Option> Options { get; set; }
        public virtual ICollection<Option> Options1 { get; set; }
    }
}
