//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEEntity.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public byte uid { get; set; }
        public string name { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int score { get; set; }
        public byte Status { get; set; }
    }
}
